# Generated by Django 3.1.5 on 2021-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210108_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
